//Generated by mkdefs.py
#ifndef DEFS_H_
#define DEFS_H_
#define SECTOR_SIZE	(0x200)
#define BOOTLOADER_BASE	(0x7c00)
#define STACK_BASE	(0x7c00)
#define OSLOADER_BASE	(0x7e00)
#define SMAP_ADDR	(0x7e00+0x2800)
#define SMAP_ENTRY_SIZE	(24)
#define KERNEL_BASE	(0x80000000)
#define KERNEL_SECTOR_BASE	(1024)
#endif
